### ISSUE TITLE
headless_news v2 is not working with ext:news v11 ? 

### ISSUE THREAD

**Issue by sivaprasad1988** [TYPO3-Headless/headless_news#24]
It is pertaining to  headless_news **v2.0.0** and news **v11.0.0**. With ext:news V11 onwards there is a new Ctype registered instead of list_type. Hence the TS Needs to be altered a bit
`
// Since there new content element ext:news 11

tt_content{
    key.field = CType
    news_pi1 = USER
    news_pi1 {
        userFunc = TYPO3\CMS\Extbase\Core\Bootstrap->run
        vendorName = GeorgRinger
        extensionName = News
        pluginName = Pi1
        controller = News
        view < plugin.tx_news.view
        persistence < plugin.tx_news.persistence
        settings < plugin.tx_news.settings
        settings {
          dateFormat = TEXT
          dateFormat = M d Y
          dateTimeFormat = TEXT
          dateTimeFormat = Y-m-d H:i:s
        }
    }
}
`

**Comment by juliasaurin** [comment]
Hey, this is not working. this configuration will override all content information.

**Comment by sivaprasad1988** [comment]
Hi @juliasaurin , Many thanks for the feedback. we could get all the information related to content elements in the fluidtemplate itself. So my idea was to override the template and add this information. For instance, the following code gets content element information, 
```
"contentElementInfo":
  <f:format.raw>
      <f:format.json value="{
              0: contentObjectData
          }"/>
  </f:format.raw>,
```

**Comment by KrohnMi** [comment]
Should work right now as solved by https://github.com/TYPO3-Headless/headless_news/pull/28

I think this can be closed

**Comment by lukaszuznanski** [comment]
closing, thank you
